In [1]:
import pandas as pd
import numpy as np
import seaborn as sb
import matplotlib.pyplot as plt

sb.set()

### Gym Members Dataset

#### Import Gym Members Dataset

In [2]:
exercise_df = pd.read_csv('../datasets/gym_members_exercise_tracking.csv')

exercise_df.rename(columns={'Weight (kg)':'Weight',
                            'Height (m)':'Height',
                            'Session_Duration (hours)':'Duration',
                            'Water_Intake (liters)':'Water_Intake',
                            'Workout_Frequency (days/week)':'Frequency'},
                            inplace=True)

exercise_df.head()

,Age,Gender,Weight,Height,Max_BPM,Avg_BPM,Resting_BPM,Duration,Calories_Burned,Workout_Type,Fat_Percentage,Water_Intake,Frequency,Experience_Level,BMI
0,56,Male,88.3,1.71,180,157,60,1.69,1313.0,Yoga,12.6,3.5,4,3,30.20
1,46,Female,74.9,1.53,179,151,66,1.30,883.0,HIIT,33.9,2.1,4,2,32.00
2,32,Female,68.1,1.66,167,122,54,1.11,677.0,Cardio,33.4,2.3,4,2,24.71
3,25,Male,53.2,1.70,190,164,56,0.59,532.0,Strength,28.8,2.1,3,1,18.41
4,38,Male,46.1,1.79,188,158,68,0.64,556.0,Strength,29.2,2.8,3,1,14.39

In [3]:
print('Data Type: ', type(exercise_df))
print('Data Dimension: ', exercise_df.shape)

Data Type:  <class 'pandas.core.frame.DataFrame'>
Data Dimension:  (973, 15)

In [4]:
exercise_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 973 entries, 0 to 972
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Age               973 non-null    int64
 1   Gender            973 non-null    object
 2   Weight            973 non-null    float64
 3   Height            973 non-null    float64
 4   Max_BPM           973 non-null    int64
 5   Avg_BPM           973 non-null    int64
 6   Resting_BPM       973 non-null    int64
 7   Duration          973 non-null    float64
 8   Calories_Burned   973 non-null    float64
 9   Workout_Type      973 non-null    object
 10  Fat_Percentage    973 non-null    float64
 11  Water_Intake      973 non-null    float64
 12  Frequency         973 non-null    int64
 13  Experience_Level  973 non-null    int64
 14  BMI               973 non-null    float64
dtypes: float64(7), int64(6), object(2)
memory usage: 114.2+ KB

In [5]:
exercise_df.describe()

,Age,Weight,Height,Max_BPM,Avg_BPM,Resting_BPM,Duration,Calories_Burned,Fat_Percentage,Water_Intake,Frequency,Experience_Level,BMI
count,973.000000,973.000000,973.00000,973.000000,973.000000,973.000000,973.000000,973.000000,973.000000,973.000000,973.000000,973.000000,973.000000
mean,38.683453,73.854676,1.72258,179.883864,143.766701,62.223022,1.256423,905.422405,24.976773,2.626619,3.321686,1.809866,24.912127
std,12.180928,21.207500,0.12772,11.525686,14.345101,7.327060,0.343033,272.641516,6.259419,0.600172,0.913047,0.739693,6.660879
min,18.000000,40.000000,1.50000,160.000000,120.000000,50.000000,0.500000,303.000000,10.000000,1.500000,2.000000,1.000000,12.320000
25%,28.000000,58.100000,1.62000,170.000000,131.000000,56.000000,1.040000,720.000000,21.300000,2.200000,3.000000,1.000000,20.110000
50%,40.000000,70.000000,1.71000,180.000000,143.000000,62.000000,1.260000,893.000000,26.200000,2.600000,3.000000,2.000000,24.160000
75%,49.000000,86.000000,1.80000,190.000000,156.000000,68.000000,1.460000,1076.000000,29.300000,3.100000,4.000000,2.000000,28.560000
max,59.000000,129.900000,2.00000,199.000000,169.000000,74.000000,2.000000,1783.000000,35.000000,3.700000,5.000000,3.000000,49.840000

#### Data Cleaning and Feature Engineering

In [6]:
# check if everyone has the right BMI based on weight and height values
incorrect_bmi_rows = []

for index, row in exercise_df.iterrows():
    if row['BMI'] != round(row['Weight']/(row['Height']**2),2):
        incorrect_bmi_rows.append(index)

incorrect_bmi_rows

# all the BMI recorded is correct

[]

In [7]:
# dropping experience level as it is an arbitraury value that may not be the same comparison or scale for everyone

exercise_df = exercise_df.drop(columns=['Experience_Level'])

exercise_df.head()

,Age,Gender,Weight,Height,Max_BPM,Avg_BPM,Resting_BPM,Duration,Calories_Burned,Workout_Type,Fat_Percentage,Water_Intake,Frequency,BMI
0,56,Male,88.3,1.71,180,157,60,1.69,1313.0,Yoga,12.6,3.5,4,30.20
1,46,Female,74.9,1.53,179,151,66,1.30,883.0,HIIT,33.9,2.1,4,32.00
2,32,Female,68.1,1.66,167,122,54,1.11,677.0,Cardio,33.4,2.3,4,24.71
3,25,Male,53.2,1.70,190,164,56,0.59,532.0,Strength,28.8,2.1,3,18.41
4,38,Male,46.1,1.79,188,158,68,0.64,556.0,Strength,29.2,2.8,3,14.39

In [8]:
# rate 1-5 for fitness index score for each of the following category

# Underweight (<18.5) = Score 1
# Normal (18.5 - 24.9) = Score 5
# Overweight (25 - 29.9) = Score 3
# Obesity (30 - 34.9) = Score 2
# Morbid Obesity (>35) = Score 1

for index, row in exercise_df.iterrows():
    if row['BMI'] < 18.5:
        exercise_df.loc[index, 'BMI_score'] = 1
    elif row['BMI'] >= 18.5 or row['BMI'] <= 24.9:
        exercise_df.loc[index, 'BMI_score'] = 5
    elif row['BMI'] >= 25 or row['BMI'] <= 29.9:
        exercise_df.loc[index, 'BMI_score'] = 3
    elif row['BMI'] >= 30 or row['BMI'] <= 34.9:
        exercise_df.loc[index, 'BMI_score'] = 2
    else:
        exercise_df.loc[index, 'BMI_score'] = 1

exercise_df.head()

,Age,Gender,Weight,Height,Max_BPM,Avg_BPM,Resting_BPM,Duration,Calories_Burned,Workout_Type,Fat_Percentage,Water_Intake,Frequency,BMI,BMI_score
0,56,Male,88.3,1.71,180,157,60,1.69,1313.0,Yoga,12.6,3.5,4,30.20,5.0
1,46,Female,74.9,1.53,179,151,66,1.30,883.0,HIIT,33.9,2.1,4,32.00,5.0
2,32,Female,68.1,1.66,167,122,54,1.11,677.0,Cardio,33.4,2.3,4,24.71,5.0
3,25,Male,53.2,1.70,190,164,56,0.59,532.0,Strength,28.8,2.1,3,18.41,1.0
4,38,Male,46.1,1.79,188,158,68,0.64,556.0,Strength,29.2,2.8,3,14.39,1.0

In [11]:
# age    target heart rate     max heart rate
# 25           98-166                195
# 35           93-157                185
# 45           88-149                175
# 55           83-140                165
# 65           78-132                155

# Healthy resting heart rate is between 50-100 heartbeats per min

for index, row in exercise_df.iterrows():
    if row['Age'] < 35 and (row['Avg_BPM'] < 98 and row['Avg_BPM'] > 166):
        exercise_df.loc[index, 'Avg_BPM_Score'] = 'Unhealthy'

In [17]:
exercise_df.loc[(exercise_df['Age'] < 35) & (exercise_df['Avg_BPM'] < 98) & (exercise_df['Avg_BPM'] > 166)]

Empty DataFrame
Columns: [Age, Gender, Weight, Height, Max_BPM, Avg_BPM, Resting_BPM, Duration, Calories_Burned, Workout_Type, Fat_Percentage, Water_Intake, Frequency, BMI, BMI_score]
Index: []